### ISSUE TITLE
Unhandled exception. TwitchLib.Api.Core.Exceptions.BadGatewayException: The API answered with a 502 Bad Gateway. Please retry your request

### ISSUE THREAD

**Issue by A5ho9999** [TwitchLib/TwitchLib#1049]
Having an issue that appeared a couple days ago. Doesn't seem to be issue with my code as it catches any exceptions to prevent crashes, so it must be coming from here. Please look into it

```
Unhandled exception. TwitchLib.Api.Core.Exceptions.BadGatewayException: The API answered with a 502 Bad Gateway. Please retry your request
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Services.LiveStreamMonitorService.GetLiveStreamersAsync()
   at TwitchLib.Api.Services.LiveStreamMonitorService.UpdateLiveStreamersAsync(Boolean callEvents)
   at TwitchLib.Api.Services.LiveStreamMonitorService.OnServiceTimerTick()
   at TwitchLib.Api.Services.Core.ServiceTimer.TimerElapsedAsync(Object sender, ElapsedEventArgs e)
   at TwitchLib.Api.Services.Core.ServiceTimer.<.ctor>b__5_0(Object sender, ElapsedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()```

**Comment by swiftyspiffy** [comment]
Hi. May I ask what version of the library you are using? I thought this was fixed. If you aren't using the latest pre-release (dev branch) nuget build, can you give that a go?

**Comment by A5ho9999** [comment]
Hello, I was using just the standard TwitchLib Package (currently v3.2.0). I will switch to the pre-release builds and let you know if the issue continues. Thank you

**Comment by A5ho9999** [comment]
Issue appears to be fixed with the pre-release, thank you :)
