### ISSUE TITLE
calling GetStreamsMetadataAsync throws exeption

### ISSUE THREAD

**Issue by antedebaas** [TwitchLib/TwitchLib#1065]
When calling 
`await api.Helix.Streams.GetStreamsMetadataAsync(null,null,1,null,null,"all",new List<string> { user.Id },null)).StreamsMetadatas`

i get the following exception:
```
Unhandled exception. System.Net.Http.HttpRequestException: Something went wrong during the request! Please try again later
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

it does work when i call GetStreamsAsync with the same vars in the same codeblock

**Comment by iProdigy** [comment]
That endpoint was removed by twitch: https://discuss.dev.twitch.tv/t/deprecation-of-the-helix-get-streams-metadata-endpoint/26407

**Comment by antedebaas** [comment]
well that makes sence.
Do you know any other way to get the game played from a stream? or is Tags the way to do it now?

**Comment by iProdigy** [comment]
You should use `GetStreamsAsync` and the `Stream` object contains `GameId`/`GameName`

**Comment by antedebaas** [comment]
Unfortionatly that does not give me the last stream, its just for active streams. Any other one i can use for that?

**Comment by swiftyspiffy** [comment]
`GetStreamsMetadata` worked to get stream data on streams that are no longer live? That's news to me, and doesn't sound intentional by Twitch 🤔

**Comment by antedebaas** [comment]
Well I don’t know. But that was what I was trying

**Comment by Syzuna** [comment]
in that case you want api.Helix.Channels.GetChannelInformationAsync(params); where api is your TwitchAPI object.

**Comment by swiftyspiffy** [comment]
Ya, sounds like `GetChannelInformation` is what you're looking for. Will close this. Feel free to reopen if needed.
