### ISSUE TITLE
code stopped working

### ISSUE THREAD

**Issue by jcmag** [TwitchLib/TwitchLib#1078]
Hi,

I have an app that was working fine until now, but now I can't anymore retrieve channels videos, I get "The resource you tried to access was not valid" errors.

My code successfully retrieves an access token, then I call: 

`var usersResponse = await api.Helix.Users.GetUsersAsync(null, new List<string> {account});`

which retrieves the user, and I get the ID:

`var userId = usersResponse.Users[0].Id;`

(in my test userId=118943611)

but then, when I call:

`var streams = await api.V5.Channels.GetChannelVideosAsync(userId, 20);`

I get an exception:

 TwitchLib.Api.Core.Exceptions.BadResourceException
  HResult=0x80131500
  Message=The resource you tried to access was not valid.
  Source=TwitchLib.Api.Core
  StackTrace:
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TwitchApp.<ProcessRequestAsync>d__2.MoveNext() in C:\Users\jcmag\Documents\MyProjects\TwitchApp\TwitchApp.ashx.cs:line 60

Any idea of the problem?

**Comment by Mahsaap** [comment]
This was likely during the 24hr outage, I believe
 there is one more outage for 48hrs then its permenent

**Comment by Mahsaap** [comment]
I was wrong, next one is permanent.  https://blog.twitch.tv/en/2021/07/15/legacy-twitch-api-v5-shutdown-details-and-timeline/

**Comment by LuckyNoS7evin** [comment]
The 24 hour outage is still ongoing until 7pm GMT 23/2/2022. Then on the 28th Feb v5 will be no more
