### ISSUE TITLE
TwitchLib is throwing exceptions on Sub/Gifted Sub events

### ISSUE THREAD

**Issue by StephenMP** [TwitchLib/TwitchLib#446]
When a Sub/Gifted Sub event roles through, TwitchLib throws a System.TypeLoadException. I'm using TwitchLib.Client v3.0.4

**Stack Trace**
System.TypeLoadException: Could not load type 'TwitchLib.Client.Models.AnonGiftedSubscription' from assembly 'TwitchLib.Client.Models, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.
   at TwitchLib.Client.TwitchClient.HandleUserNotice(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient.HandleIrcMessage(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient._client_OnMessage(Object sender, OnMessageEventArgs e)
   at TwitchLib.Communication.Clients.WebSocketClient.<<StartListenerTask>b__68_0>d.MoveNext()

**Comment by Mahsaap** [comment]
Use individual pre release versions of the lib. Known issue
