### ISSUE TITLE
LiveStreamMonitorService crashes program

### ISSUE THREAD

**Issue by Nectura** [TwitchLib/TwitchLib#447]
Hey, so after some time that my program runs this exception usually happens and crashes it.
I'm not really sure if I can even Try-Catch it, but I can't really disable the monitor without breaking functionality. I'm probably misreading it or missing something, any tips?

- I am on the latest standalone lib parts from the NuGet store, not the All-In-One as of now, also happened on that one before I switched.

`Unhandled Exception: TwitchLib.Api.Core.Exceptions.BadGatewayException: The API answered with a 502 Bad Gateway. Please retry your request
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Services.LiveStreamMonitorService.GetLiveStreamersAsync()
   at TwitchLib.Api.Services.LiveStreamMonitorService.UpdateLiveStreamersAsync(Boolean callEvents)
   at TwitchLib.Api.Services.LiveStreamMonitorService.OnServiceTimerTick()
   at TwitchLib.Api.Services.Core.ServiceTimer.TimerElapsedAsync(Object sender, ElapsedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by RRickkert** [comment]
https://discuss.dev.twitch.tv/t/502-bad-gateway-on-api-calls-causing-up-to-60-failure-rate-for-cron-jobs/1574
Looks like Twitch can just be very unstable at moments. And there's no try catch mechanism build in the livestream monitor.
R.I.P.
I guess that's something that should be added sometime soon :D

**Comment by SPDevDE** [comment]
Unfortunately, I have a very similar issue. The LIveStreamMonitor and the FollowerService were running fine for a long time but suddenly, since a few days now, it is breaking my application.

> Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
> Ausnahmeinformationen: System.Net.WebException
>   bei System.Net.HttpWebRequest.EndGetResponse(System.IAsyncResult)
>   bei System.Net.Http.HttpClientHandler.GetResponseCallback(System.IAsyncResult)

> Ausnahmeinformationen: System.Net.Http.HttpRequestException
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
>    bei TwitchLib.Api.Core.Internal.TwitchHttpClientHandler+<SendAsync>d__2.MoveNext()
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
>    bei TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(System.String, System.String, System.String, TwitchLib.Api.Core.Enums.ApiVersion, System.String, System.String)
>    bei TwitchLib.Api.Core.ApiBase.GenerateServerBasedAccessToken()
>    bei TwitchLib.Api.Core.ApiBase.GetAccessToken(System.String)
>    bei TwitchLib.Api.Core.ApiBase.TwitchGetGenericAsync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, TwitchLib.Api.Core.Enums.ApiVersion, System.Collections.Generic.List`1<System.Collections.Generic.KeyValuePair`2<System.String,System.String>>, System.String, System.String, System.String)
>    bei TwitchLib.Api.Helix.Users.GetUsersFollowsAsync(System.String, System.String, Int32, System.String, System.String)
>    bei TwitchLib.Api.Services.Core.FollowerService.NameBasedMonitor+<GetUsersFollowsAsync>d__2.MoveNext()


And I have no idea what the best solution for error handling could be at it's current version.

**Comment by jackie0100** [comment]
I too is getting some issues with this, below I have a callstack;

Unhandled exception. TwitchLib.Api.Core.Exceptions.BadGatewayException: The API answered with a 502 Bad Gateway. Please retry your request
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.GenerateServerBasedAccessToken()
   at TwitchLib.Api.Core.ApiBase.GetAccessToken(String accessToken)
   at TwitchLib.Api.Core.ApiBase.TwitchGetGenericAsync[T](String resource, ApiVersion api, List`1 getParams, String accessToken, String clientId, String customBase)
   at TwitchLib.Api.Helix.Streams.GetStreamsAsync(String after, List`1 communityIds, Int32 first, List`1 gameIds, List`1 languages, String type, List`1 userIds, List`1 userLogins)
   at TwitchLib.Api.Services.Core.LiveStreamMonitor.NameBasedMonitor.GetStreamsAsync(List`1 channels)
   at TwitchLib.Api.Services.LiveStreamMonitorService.GetLiveStreamersAsync()
   at TwitchLib.Api.Services.LiveStreamMonitorService.UpdateLiveStreamersAsync(Boolean callEvents)
   at TwitchLib.Api.Services.LiveStreamMonitorService.OnServiceTimerTick()
   at TwitchLib.Api.Services.Core.ServiceTimer.TimerElapsedAsync(Object sender, ElapsedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by swiftyspiffy** [comment]
I believe this has been fixed. Please reopen if needed.
