### ISSUE TITLE
Some kind of substring exception

### ISSUE THREAD

**Issue by behealed** [TwitchLib/TwitchLib#484]
I don't know where this exception is, but it doesn't seem to be in my code, so I'm posting the exception text here. I'm not trying to be unhelpful, but I only use the precompiled version of twitchlib, so I don't have any detailed info more than this exception text....

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at TwitchLib.Client.Models.Extractors.EmoteExtractor.GetEmote(String emoteData, String emoteId, String message, Boolean single)
   at TwitchLib.Client.Models.Extractors.EmoteExtractor.<Extract>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TwitchLib.Client.Models.EmoteSet..ctor(String rawEmoteSetString, String message)
   at TwitchLib.Client.Models.ChatMessage..ctor(String botUsername, IrcMessage ircMessage, MessageEmoteCollection& emoteCollection, Boolean replaceEmotes)
   at TwitchLib.Client.TwitchClient.HandlePrivMsg(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient.HandleIrcMessage(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient._client_OnMessage(Object sender, OnMessageEventArgs e)
   at TwitchLib.Communication.Clients.WebSocketClient.<<StartListenerTask>b__68_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at TwitchLib.Communication.Clients.WebSocketClient.CleanupServices()
   at TwitchLib.Communication.Clients.WebSocketClient.Close(Boolean callDisconnect)
   at TwitchLib.Client.TwitchClient.Disconnect()
   at TwitchChatLurker_dev.Form1.Bot.Disconnect()
   at TwitchChatLurker_dev.Form1.timer1_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at TwitchLib.Client.Models.Extractors.EmoteExtractor.GetEmote(String emoteData, String emoteId, String message, Boolean single)
   at TwitchLib.Client.Models.Extractors.EmoteExtractor.<Extract>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TwitchLib.Client.Models.EmoteSet..ctor(String rawEmoteSetString, String message)
   at TwitchLib.Client.Models.ChatMessage..ctor(String botUsername, IrcMessage ircMessage, MessageEmoteCollection& emoteCollection, Boolean replaceEmotes)
   at TwitchLib.Client.TwitchClient.HandlePrivMsg(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient.HandleIrcMessage(IrcMessage ircMessage)
   at TwitchLib.Client.TwitchClient._client_OnMessage(Object sender, OnMessageEventArgs e)
   at TwitchLib.Communication.Clients.WebSocketClient.<<StartListenerTask>b__68_0>d.MoveNext()<---

**Comment by behealed** [comment]
I did check the getemotes code, and it only has one substring call:

string name = message.Substring(startIndex, (endIndex - startIndex) + 1);

So that line is where this exception is occurring. Can you put that line inside of a try catch or something? I have no idea why it is failing, I have no code in my program that does anything with emotes whatsoever, if it's calling getemotes it isn't because I asked it to, it must be something happening internally.

**Comment by Syzuna** [comment]
when did this exception happen? there was an incident with Twitchs Emote System a few days ago that killed every bot out there most likely bcs of unparsable emoteIds/names

**Comment by behealed** [comment]
This exception happened just a few minutes ago, right before I posted this.

**Comment by behealed** [comment]
And I just checked to make sure I'm on the latest version of twitchlib

**Comment by behealed** [comment]
I've seen this exception multiple times

**Comment by behealed** [comment]
I'd fork it and add the try catch myself, but.... I don't know enough about the calling functions to know if they also will crash if GetEmote returns a null.

**Comment by Syzuna** [comment]
TwitchLibs Emote code always was kinda shacky. we are working on a rewrite of most of TwitchLib atm but its time consuming. will try to investigate later. 1 am for me :D

**Comment by behealed** [comment]
This error is definitely crashing my whole bot at least once every day. I'm curious, is there some kind of way for me to prevent my entire c# application from crashing, just because the code contained in this dll is crashing? What I mean is, I have multiple bots open, and if ONE of the bots happens to have this exception, it crashes not only that bot, but my entire app, which crashes ALL my bots. I'm considering to spawn multiple instances of my exe, with each exe running just a single bot. But before I do all that refactoring, I was just curious if anyone knows a more elegant way... like to make it so that if the exception occurs in this GetEmote(), that it will at the very most crash just the one Bot(), and not crash them all? If not then I guess I'll have to run multiple exe's for now, until this is fixed of course. :)

**Comment by LuckyNoS7evin** [comment]
> This error is definitely crashing my whole bot at least once every day. I'm curious, is there some kind of way for me to prevent my entire c# application from crashing, just because the code contained in this dll is crashing? What I mean is, I have multiple bots open, and if ONE of the bots happens to have this exception, it crashes not only that bot, but my entire app, which crashes ALL my bots. I'm considering to spawn multiple instances of my exe, with each exe running just a single bot. But before I do all that refactoring, I was just curious if anyone knows a more elegant way... like to make it so that if the exception occurs in this GetEmote(), that it will at the very most crash just the one Bot(), and not crash them all? If not then I guess I'll have to run multiple exe's for now, until this is fixed of course. :)

You could put exception handling around GetEmote() when you call it. This should catch the exception and not completely crash the bot

**Comment by swiftyspiffy** [comment]
I don't think this is happening anymore, I've not encountered it or seen any reports of it. Please reopen if it is though.
